### ISSUE TITLE
license key lost

### ISSUE THREAD

**Issue by csreaper** [MitchTalmadge/AMP-dockerized#171]
I set everything up correctly but after logging in I get the following message

Problem:
AMP has lost its licence key due to a hardware or system configuration change. Please re-enter your licence key under Configuration -> New Instance Defaults. You may also need to reactivate your existing instances on this host.

**Comment by MitchTalmadge** [comment]
This usually happens because of the MAC Address, can you share your configuration for the container? Either the docker compose file or the command you use to run it or the config page if on Unraid (and block out any passwords or such)

Thankz!

**Comment by csreaper** [comment]
# This configuration creates one ADS instance, which can be used to create multiple "child" instances.
# This is a good choice if you want to run multiple game servers, even of different types.
version: "3"
services:
  amp:
    container_name: 12_AMP-GameServer
    image: mitchtalmadge/amp-dockerized:latest
    network_mode: bridge
    mac_address: 02:42:AC:XX:XX:XX # Please see the README about this field.
    
    ports:
      - 8080:8080
      - 25565:25565 # Example port for Minecraft Java server.
      - 19132:19132/udp #Minecraft Bedrock (Crossplay)
      - 34197:34197/udp #StarBound
    volumes:
      - xxxxxx:/home/amp/.ampdata
    environment:
      - "UID=xxxx" # Change according to which user on the host will own the ampdata volume.
      - "GID=xxx"
      - "TZ=Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - "LICENCE=eef67xxx-xxxx-xxxx-xxx-xxxx"
      - "MODULE=ADS"
    restart: unless-stopped

**Comment by IceOfWraith** [comment]
You left the defaults for the config. You need to put actual values for the `xx:xx:xx` parts of the MAC Also the UID and GID along with the LICENSE need to be filled in. The UID and GID can be obtained for the user you want to run it as by doing `id youruser` on the host.

**Comment by csreaper** [comment]
First of all, thank you, I would like to clarify again. I have made the MAC, license and UID unrecognizable and of course they are filled out in the correct config. I would like to say that it works at the beginning, but the key is lost after logging in again via the web GUI.

**Comment by csreaper** [comment]
First of all, thank you, I would like to clarify again. I have made the MAC, license and UID unrecognizable and of course they are filled out in the correct config. I would like to say that it works at the beginning, but the key is lost after logging in again via the web GUI.

**Comment by IceOfWraith** [comment]
Can you share the file with those values left in? It's not a security issue to share them. Also, run `id yourusername` and share the numbers it outputs.

**Comment by IceOfWraith** [comment]
Don't share the license key itself, of course!

**Comment by csreaper** [comment]
```
# This configuration creates one ADS instance, which can be used to create multiple "child" instances.
# This is a good choice if you want to run multiple game servers, even of different types.
version: "3"
services:
  amp:
    container_name: 12_AMP-GameServer
    image: mitchtalmadge/amp-dockerized:latest
    network_mode: bridge
    mac_address: 02:42:AC:32:F5:02 # Please see the README about this field.
    
    ports:
      - 8080:8080
      - 25565:25565 # Example port for Minecraft Java server.
      - 19132:19132/udp #Minecraft Bedrock (Crossplay)
      - 34197:34197/udp #StarBound
    volumes:
      - /volume1/docker/12_AMP-GameServer:/home/amp/.ampdata
    environment:
      - "UID=1026" # Change according to which user on the host will own the ampdata volume.
      - "GID=100"
      - "TZ=Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - "LICENCE=eef67d11-ff80-424d-9fbc-e1410496a60d"
      - "MODULE=ADS"
    restart: unless-stopped
```



`uid=1026(amp) gid=100(users) groups=100(users) `
