### ISSUE TITLE
SFTP: Unsupported File Open Mode

### ISSUE THREAD

**Issue by dunklesToast** [MitchTalmadge/AMP-dockerized#54]
When I try to connect via SFTP I get a "Unsupported File Open Mode" by my FTP Client, Cyberduck. 

That's my docker-compose.yml

```yml
version: "3.8"

services:
  amp:
    image: mitchtalmadge/amp-dockerized
    mac_address: 02:42:AC:6A:CF:39
    volumes:
      - mc_data:/home/amp/.ampdata
    ports:
      - 25565:25565
      - 127.0.0.1:8080:8080
      - 127.0.0.1:2223:2223/udp
      - 127.0.0.1:2223:2223/tcp
    environment:
      LICENCE: "X"
      MODULE: "Minecraft"
      TZ: "Europe/Berlin"

volumes:
  minecraft_jahrgangsprojekt:
```
